### ISSUE TITLE
incompatible modules in package

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_classic_laf#10]
The zip file 2.0.5.1.0 contains in folder modules_v4 both modules:
- compact_themes_adjuster
- vesta_classic_look_and_feel
If both are uploaded and enabled this results in an error.

compact_themes_adjuster has to be removed.

**Comment by ric2016** [comment]
vesta_classic_look_and_feel is basically a renamed compact_themes_adjuster.

The folder 'compact_themes_adjuster' now just contains an 'empty' module.php that cannot be activated, so I'm not sure how it is possible to enable it?

**Comment by hartenthaler** [comment]
You are right! I have not checked that  'compact_themes_adjuster' is empty. I just deleted all vesta modules at my server, uploaded all folders from the zip-file and got a 500 error. Then I disabled both, 'vesta_classic_look_and_feel' and 'compact_themes_adjuster' and now everything is working fine. Then I enabled  'vesta_classic_look_and_feel' and again everything is ok. So I assumed that it was the "old" module  'compact_themes_adjuster'. But now I enabled the empty  'compact_themes_adjuster' again and now there is everything still ok. Strange. Maybe it was something else. You can close this issue.

**Comment by ric2016** [comment]
I'll add a note to the zip file to make this clearer.
