### ISSUE TITLE
2.1.10.0.0 - Compact layout for edit dialogs does not work with Rural theme

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#106]
**Control panel / Modules / ⚶ Vesta Classic Look & Feel / Preferences / Edit dialogs / Use compact layout**

> "Display all edit dialogs using a more compact layout, which also omits the standard header and footer. This only affects standard and specific custom themes."

In webtrees v2.0.x the compact layout for the edit dialogs works fine with [Rural theme](https://github.com/jon48/webtrees-theme-rural).

But in webtrees v2.1.10 it doesn't work anymore with the Rural Theme.

Is it possible to fix this?

Tested with:
- webtrees v2.1.10
- Vesta Webtrees Custom Modules v2.1.10.0.0
- Rural Theme v2.1.8-v.1

**Comment by ric2016** [comment]
It is certainly possible (although it is always tricky to align separate custom modules), but I'm not sure anymore whether it's a good idea in general to adjust the layout of custom themes.

This has been discussed a bit [here](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues/80). I think after that I decided to not adjust the Rural theme edit dialogs any more. Still not sure about this.

**Comment by TheDutchJewel** [comment]
>I think after that I decided to not adjust the Rural theme edit dialogs any more. Still not sure about this.
> ric2016 closed this as completed

This is very unfortunate. Especially the lack of the compact layout for the edit dialog in the Rural theme is a big miss.
Using the default webtrees themes for data entry is not an option because they use too much space.

Is it possible to apply the changes for the editing dialog in the Rural theme through the CSS module?

If so, how?

**Comment by ric2016** [comment]
> Using the default webtrees themes for data entry is not an option because they use too much space.

I don't understand this part, 'compact layout' is supposed to address this?

**Comment by ric2016** [comment]
> Is it possible to apply the changes for the editing dialog in the Rural theme through the CSS module?

This seems to work (similar for footer), may have to be extended for specific dialogs:

```
body[class~="wt-route-EditFactPage"] > header {
  display: none;
}
```

**Comment by TheDutchJewel** [comment]
> > Using the default webtrees themes for data entry is not an option because they use too much space.
> 
> I don't understand this part, 'compact layout' is supposed to address this?

I meant the option 'Use compact layout' for the Edit dialogs, which also omits the standard header and footer.:
![afbeelding](https://user-images.githubusercontent.com/46184729/210055883-2f54898c-dd20-463c-b42b-5c535157eaab.png)

**Comment by TheDutchJewel** [comment]
> body[class~="wt-route-EditFactPage"] > header {
>   display: none;
> }

Thanks, this works fine!
