### ISSUE TITLE
Request: more compact layout editor dialog for webtrees 2.1.x

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#107]
This is my editor dialog in webtrees 2.0.x when I have most used tags open:

![afbeelding](https://user-images.githubusercontent.com/46184729/206867973-5dac1eb7-f327-4f51-b2e8-d4dc533f0be0.png)

Here the same dialog in webtrees 2.1.x:

![afbeelding](https://user-images.githubusercontent.com/46184729/206868609-f6546faf-0c20-446a-af18-bcc25f293a81.png)

What a waste of space!

This is currently the main reason for me to keep using webtrees 2.0.x for adding to and updating the family tree.

Is it possible to create a more compact dialog like in webtrees 2.0.x?

**Comment by ric2016** [comment]
Indeed it doesn't seem to be any more compact than the standard dialog (except for skipping header and footer).

I have to admit I didn't really notice this - it probably occurred when switching to 2.1. Anyway I'll address this.

(By the way, note that Vesta also allows to to get rid of any unwanted tags in this dialog - there are a lot more compared to the 2.0 version)

**Comment by TheDutchJewel** [comment]
> (By the way, note that Vesta also allows to to get rid of any unwanted tags in this dialog - there are a lot more compared to the 2.0 version)

Do you mean: `Control panel / Modules / ⚶ Vesta Facts and events`?

**Comment by ric2016** [comment]
No, [see description here](https://www.webtrees.net/index.php/en/forum/4-customising/37154-customization-of-gedcom-tag-visibility).

**Comment by TheDutchJewel** [comment]
Great, thank you!

That looks much better::
![afbeelding](https://user-images.githubusercontent.com/46184729/206896185-55863313-f5ea-4204-9604-e688b4c7ceed.png)

Still, it could be even more compact by having less space between the rows, as in the 2.0 version.

**Comment by ric2016** [comment]
Layout is adjusted now (Release 2.1.13.0.0)
