### ISSUE TITLE
Collapsing and unfolding citation details

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#108]
> (By the way, note that Vesta also allows to to get rid of any unwanted tags in this dialog - there are a lot more compared to the 2.0 version)
> 
> _Originally posted by @ric2016 in https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues/107#issuecomment-1345361412_

      
When collapsing and unfolding citation details from, say, BIRT, this also works into the events CHR/CREM/BURI.

But not for DEAT, which works separately.

Is that intentional, or is it a bug?

**Comment by ric2016** [comment]
This is very likely unintentional. I actually assumed it was a webtrees issue, but it seems to be Vesta-specific.

**Comment by ric2016** [comment]
Actually (just tested this on the demo server) this is a webtrees bug after all.
There are multiple elements in the DOM with the same id (e.g. 'collapse-15'), which leads to this issue. Can you create a webtrees issue for this?

**Comment by TheDutchJewel** [comment]
> Actually (just tested this on the demo server) this is a webtrees bug after all. There are multiple elements in the DOM with the same id (e.g. 'collapse-15'), which leads to this issue. Can you create a webtrees issue for this?

Done: [issue#4654](https://github.com/fisharebest/webtrees/issues/4654)
