### ISSUE TITLE
'PLAC' within all 'INDI' events

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#109]
![afbeelding](https://user-images.githubusercontent.com/46184729/206897208-e6b64df7-8d6d-4507-b930-fee80c40df5b.png)

Is 'PLAC' correct in this content?

I assume 'PLAC'" should be 'DEAT'.

Same problem in other tags and events.

**Comment by ric2016** [comment]
Yes, 'PLAC' (also 'INDI' in case of 'FAM' events) is just a placeholder here which I forgot to replace properly.

**Comment by ric2016** [comment]
This is very likely unintentional. I actually assumed it was a webtrees issue, but it seems to be Vesta-specific.
