### ISSUE TITLE
v2.0.5.2.0 - Windows key + Left arrow - scaling problem

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#11]
When I adjust the size of the browser page with the `Windows key + the left arrow`, the right side of boxes with the family members, does not look good:
![afbeelding](https://user-images.githubusercontent.com/46184729/84621177-2e3bdc80-aeda-11ea-9c7e-55762a411f96.png)

The problem seems to be caused by the _Vesta Webtrees Custom Module 'Classic Look & Feel'_, which I enabled to use the custom prefixes for XREFs. 
If I disable this module, everything looks fine:
![afbeelding](https://user-images.githubusercontent.com/46184729/84620660-dcdf1d80-aed8-11ea-8a2b-582fa6e595c7.png)

See also this [issue on github/jon48/webtrees-theme-rural](https://github.com/jon48/webtrees-theme-rural/issues/10) which I opened because I first thought the problem was caused by this theme.

**Tested configuration**

- webtrees v2.0.5 with modules:
- + Rural Theme 2.0.4-v.2
- + Tree View Full Screen v0.5
- + Vesta Classic Look & Feel v2.0.5.2.0
- + Vesta Extended Relationships v2.0.5.2.0
- + webtrees-fan-chart v2.0.3
- OS: Win 10 Home x64 v1909
- Device: desktop
- Screen resolution: 1920x1080
- Local web server: XAMPP portable x64 v7.3.18
- Browsers: Edge v83.0.478.45 and Firefox v77.0.1

**Comment by ric2016** [comment]
Confirmed. I'll try to fix this.

The layout of this sidebar is problematic in general, in webtrees itself. If you have very long surnames, you get a similar effect.

Internal note: It helps somewhat to disable
.dropdown-toggle {
    white-space: nowrap;
}

**Comment by ric2016** [comment]
Fixed in latest release.
