### ISSUE TITLE
2.1.13.0.1 - Error: Control panel - GEDCOM tags

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#112]
Control panel - GEDCOM tags:
![afbeelding](https://user-images.githubusercontent.com/46184729/208078114-9ae91709-6996-44d7-91af-d150abb544b2.png)

Tested with webtrees 2.1.13 and only the Vesta Webtrees Custom Modules 2.1.13.0.1 enabled.

**Comment by ric2016** [comment]
Thanks - Fixed in latest Vesta release.
