### ISSUE TITLE
v2.1.15.0.0 - Im Editiermodus lassen sich Quellen nicht ausklappen / Gedcom-Tags nicht benutzerdefiniert bearbeiten

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_classic_laf#114]
Hallo, in der aktuellen Kombination von webtrees v2.1.15 und Ihrem Add-on v2.1.15.0.0 lassen sich im Editiermodus von Ereignissen die Quellen nicht ausklappen oder dort keine benutzerdefinierte Gedcom-Tag-Einstellungen machen. Wenn ich das Add-on deaktiviere, geht das Ausklappen wieder. Können Sie bei Gelegenheit mal schauen, woran dies liegt? Vielen Dank.

**Comment by ric2016** [comment]
Fixed in release 2.1.15.0.1.

**Comment by JanSneijders** [comment]
With the combination of Webtrees 2.1.15 and the Addon 2.1.15.0.0 it is not possible to add a new name. This name is not visible after saving.
Has this been fixed in the Addon version 2.1.15.0.1?

**Comment by ric2016** [comment]
> Has this been fixed in the Addon version 2.1.15.0.1?

No, because I was not aware of the issue. Also I cannot reproduce it.
Please open a separate issue with more details.

**Comment by TheDutchJewel** [comment]
> With the combination of Webtrees 2.1.15 and the Addon 2.1.15.0.0 it is not possible to add a new name. This name is not visible after saving.

I can't reproduce this either. Works fine with me.
