### ISSUE TITLE
Problema entre los módulos vesta_classic_laf i Pedigree-Chart

### ISSUE THREAD

**Issue by BernatBanyuls** [vesta-webtrees-2-custom-modules/vesta_classic_laf#116]
Encontraba algunos problemas puntuales entre los dos módulos y Rico me ha contestado el texto siguiente:

**looked up your list of custom modules installed and found out, that the vesta_classic_look_and_feel causes the issues. Especially the option "Display nicknames before surnames", which is the cause of the error. After disabling it the chart renders perfectly.**

**Comment by ric2016** [comment]
Thanks - already reported here:
https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues/115
