### ISSUE TITLE
Option to auto-expand name

### ISSUE THREAD

**Issue by ric2016** [vesta-webtrees-2-custom-modules/vesta_classic_laf#117]
"In 1.7 the note field was always visible. when populated
However I would prefer to see the note in case the field is populated (without expanding manually)"

Add configuration option to auto-expand names
- never (default, current behavior)
- when name contains additional fields (sources/ notes)
- always

**Comment by ric2016** [comment]
Available in release 2.1.16.1.0: New option in module configuration

<img width="551" alt="names" src="https://user-images.githubusercontent.com/18174787/213882975-e4d17d83-b427-4400-bc45-06d6e2327635.png">

**Comment by juergenwolfus** [comment]
Thanks a lot for implementing this feature so quickly. It works are expected
Kind regards Juergen
