### ISSUE TITLE
Error found in Logfile

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_classic_laf#122]
> Undefined variable $tree …/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml:41</b> <b>#0 …/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(41): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()</b> #1 …/app/View.php(183): include(&#039;...&#039;) #2 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() #3 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #4 …/app/Http/ViewResponseTrait.php(54): view() <b>#5 …/modules_v4/repository_hierarchy/RepositoryHierarchy.php(1268):

**Comment by ric2016** [comment]
This apparently occurs when a view is called without a 'tree' variable, via [ViewResponseTrait](https://github.com/fisharebest/webtrees/blob/aa30352e2ad3153330fc18e198d6b9b145348abe/app/Http/ViewResponseTrait.php#L44).

The caller is another custom module in this case, who [in fact does not set this variable](https://github.com/Jefferson49/RepositoryHierarchy/blob/ee19e620cc24adfd8546be25d2c03aadaea0ca6c/RepositoryHierarchy.php#L1268).

[This probably should be handled better in webtrees as well](https://github.com/fisharebest/webtrees/blob/aa30352e2ad3153330fc18e198d6b9b145348abe/resources/views/layouts/default.phtml#L42). (Vesta code adjusted from there) - I.e. when disabling Vesta, the same error will show up in the logs via the default layout view.

**Comment by ric2016** [comment]
Fixed in latest Vesta release 2.1.16.1.3.
