### ISSUE TITLE
Classic layout or not ?

### ISSUE THREAD

**Issue by ghezibde** [vesta-webtrees-2-custom-modules/vesta_classic_laf#125]
In earlier versions of webtrees, we used to be able to add funeral information (date, place, and media object) to an individual.
This place is an important information, different from death or burial and funeral announce often contains much informations about the family of the person who just died).
We also used to add date and place information and media-object to the soldier course of an individual, particularly rich when a person is involved in a war.
This is no longer possible in recent versions (for gedcom syntax purposes i suppose).
This has been discussed in webtrees forum here https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37924-funeral-gedcom-tag#100001
Rather than create a specific module, i thought it'd make sense to handle of those points in vesta_classic-laf ?

**Comment by ric2016** [comment]
> i thought it'd make sense to handle of those points in vesta_classic-laf

No, because I don't want to support these custom tags in Vesta.

Your options are to either wait for Greg to implement the custom module, as he suggested, or to use standard GEDCOM

```
1 EVEN
2 TYPE funeral
```

which would be more compatible with GEDCOM 7 and other applications anyway.
