### ISSUE TITLE
Not compatible with webtree 2.1.17

### ISSUE THREAD

**Issue by xiaoyang2013** [vesta-webtrees-2-custom-modules/vesta_classic_laf#126]
Hi, today's test found that it is not compatible with webtree 2.1.17, prompting:
`_This version of the module is incompatible with your current webtrees version. Only webtrees versions before 2.1.17 are supported. All functionality of the module is therefore disabled. To restore functionality, either use an updated version of this module (once available) or downgrade your webtrees version (if possible)._`

**Comment by ric2016** [comment]
The note should tell you everything. What about it is unclear?
