### ISSUE TITLE
cross module reference - INDI Name icons

### ISSUE THREAD

**Issue by HerzScheisse** [vesta-webtrees-2-custom-modules/vesta_classic_laf#135]
Hey ric,

Thanks for your modules and all the work you put into it....

recently i asked the dev of the repository_hierarchy module to apply a fix for the source citation copy/paste function... https://github.com/Jefferson49/RepositoryHierarchy/issues/51 

But this doesnt work for me, because i use the vesta modules...

Dont know if this works in general or do you know a way how to handle this... Do you think its possible to add a function: individual_name.phtml to get this paste function added?

Something like: if repo_module installed, than display the icon...
`                    <?php //Additionally show icon to paste source citations?>
                    <?php if (Session::has(RepositoryHierarchy::activeModuleName() . RepositoryHierarchy::PREF_CITATION_GEDCOM . '_' . $fact->record()->tree()->id()) &&
                            boolval($repository_hierarchy->getPreference(RepositoryHierarchy::PREF_ENABLE_COPY_PASTE_CITATIONS, '0'))    ) : ?>
                        <?= view(RepositoryHierarchy::viewsNamespace() . '::edit/icon-source-citation-paste', ['fact' => $fact]) ?>
                    <?php endif ?> `
                    
Thanks,
Holger

**Comment by ric2016** [comment]
I want to avoid specific code dealing with other custom modules if at all possible.

Instead, I'll expand the configuration option so that you can still use an otherwise 'compact layout', but not for the names on the individual page. That way other modules get a chance to override the respective view.

<img width="570" alt="config" src="https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/assets/18174787/467b41cf-68af-43dc-99e1-56d5ed395c4b">

**Comment by ric2016** [comment]
Implemented in Release 2.1.18.2.1.

**Comment by HerzScheisse** [comment]
awesome!

Thank you very much for these changes. much appreciated.

**Comment by HerzScheisse** [comment]
oh, just to mention... some parts of the "choose layout" parts in admin config are not translate to german yet...

I checked weblate, but it seem the new vars are not synced yet!?

Same applies for the new badges functions.. (no hurry just want to mention it in case you are not aware of :)

**Comment by ric2016** [comment]
Thanks for the note, I forgot to update the module in weblate. The new strings are now available for translation.
