### ISSUE TITLE
problem with layout since update to 2.1.19

### ISSUE THREAD

**Issue by Joppla** [vesta-webtrees-2-custom-modules/vesta_classic_laf#143]
Hello,

I just updated webtrees en the vesta module to version 2.1.19. Now I get behind every name a "?" symbol: 
![afbeelding](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/assets/25467829/46ce89bb-d5b5-4dd5-9cb3-6e184b6e54ed)

I think, it is result of the Vesta Module. If I turn off the modules, the symbol is gone.

I have installed / use the following sub modules:

1. Vesta Classic look and feel
2. Vesta clippings art
3. Vesta common

Is it a bug or a setting?

**Comment by ric2016** [comment]
It's a setting/ promoting a new feature. Read the tooltip of the '?'
(You probably haven't seen the "What's new" message?)

Or just go directly to control panel settings > Vesta Classic Look and Feel > Name Badges.

**Comment by Joppla** [comment]
Yes, there is a tooltip.
To remove them I can simple on the red symbol?
![afbeelding](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/assets/25467829/f2f11819-2337-4357-8224-5bd2987c7932)

**Comment by ric2016** [comment]
Yes. It's just a placeholder leading you to this setting. More details are shown via the edit icon.
I'll add more documentation for this feature (#142).

You may want to delete the others as well (or restrict their visibility), they are just intended as examples.

**Comment by Joppla** [comment]
Thanks!
