### ISSUE TITLE
Drop down menu for SOUR:DATA:EVEN only shows subset of facts/events

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_classic_laf#148]
Observed with webtrees 2.1.20 and vesta 2.1.20.0.0

If editing a source, the drop down menu for SOUR:DATA:EVEN does only contain a subset of all allowed GEDCOM facts/events.

![only subset of FACT EVEN shown](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/assets/81484983/43b2c92a-f1cc-42e5-8064-e2dcc6a9ebdd)

**Comment by ric2016** [comment]
This is by design - It's configurable in the tree preferences under "Facts for source records" (i.e. in the general preferences, not Vesta-specific module preferences, because originally I intended to have all of this in webtrees core).

**Comment by Jefferson49** [comment]
Thanks! Ah, o.k.. I checked in the general vesta preferences, but did not think about the tree preferences.

However, I was using this for hundreds of sources in the last years. Is it possible that the preferences were reset during the update to vesta 2.1.20.0.0 ? Or are the preferences new?

**Comment by ric2016** [comment]
> Or are the preferences new?

No, I haven't changed anything here for a while. So it worked for you before with other event types? Maybe the preferences got reset by the webtrees upgrade, I'll have to check that.

**Comment by ric2016** [comment]
This works as designed (at least for me - i.e. I do not see the preferences reset after the latest webtrees upgrade).
