### ISSUE TITLE
Compact edit dialogs layout - wrong diacritics

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_classic_laf#15]
When in Preferences > Edit dialogs > Use compact layout is checked, then the secondary create dialog (called with '+' sign) layout displays with wrong diacritics:

![Výběr_069](https://user-images.githubusercontent.com/350656/85207027-538b7900-b326-11ea-9d40-f76c6fdc6fb1.jpg)

This is in Czech language, tested also with Polish.

**Comment by ric2016** [comment]
Fixed in latest release (2.0.6.0.3).

**Comment by jpretired** [comment]
Looks OK, thanks a lot.
