### ISSUE TITLE
Doubled navbar with JustLight theme

### ISSUE THREAD

**Issue by godzil3** [vesta-webtrees-2-custom-modules/vesta_classic_laf#150]
Hi
I'm using both classic laf and JustLight theme by Carmen. This result doubled header navbar in responsive/mobile view. Is that something with my setup or this is expected in this config?
When disabling classic laf additional navbar stop appearing but it's not a good option for me

![wide](https://github.com/user-attachments/assets/ed3ad1a8-b0f5-4e8c-82a2-5bc787b073d0)
![thin](https://github.com/user-attachments/assets/9ddf21e2-4cb7-4f1d-85d9-217da4fe34b2)

**Comment by ric2016** [comment]
Using complex custom modules from different sources can cause effects like this one, if two modules modify the same part of the user interface.

I'll check if there is a workaround for this (in a few days, I'm on holiday at the moment).
