### ISSUE TITLE
Runtime exception in combination with justlight-2.2.8

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_classic_laf#152]
Hello Richard,

I opened an issue for jc-justlight-2.2.8 (See https://github.com/JustCarmen/webtrees-theme-justlight/issues/173)

Carmen replied:
This looks like an issue with Vesta. In this version of the theme I've split up the cellphone menu into two separate menus. The primary (genealogy) and the secondary (user) menu. The file navbar-toggler doesn't exist anymore in this version. You should raise an issue at https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues

Best regards, Peter

**Comment by ric2016** [comment]
> This looks like an issue with Vesta

The basic issue is that different custom modules may conflict if they modify the same view. 
Vesta attempts to handle this conflict, which is problematic in particular if there are frequent changes in the other module.
The fix itself is easy in this case, but I may have to restrict the handling to specific justLight versions if there are further changes in the theme.
