### ISSUE TITLE
Submitting Czech translations

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_classic_laf#17]
I would like to submit Czech language translations for all Vesta modules. Is it possible to include them into the Vesta package please?
See appendix:
[vesta_modules_lang_Czech.zip](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/files/4820840/vesta_modules_lang_Czech.zip)

**Comment by ric2016** [comment]
Thank you! Custom translations are always very welcome. I'll add them in the next release.

**Comment by ric2016** [comment]
Added in latest release (2.0.6.1.0)
