### ISSUE TITLE
adding (XREF) two times to a name

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_classic_laf#35]
I'm testing the new module "[branch statistics](https://github.com/squatteur/webtrees-branch-statistics)" at the moment.
The (XREF) was added two times to names. Maybe you can check if there is already a (XREF) connected to a name before adding it a second time. But maybe the programmer of the new module "branch statistics" has to change his code.
![Screenshot (112)_LI](https://user-images.githubusercontent.com/6324175/103675845-b2da6f00-4f80-11eb-9c89-b24ef2fa60a3.jpg)

**Comment by ric2016** [comment]
The XREF is added after the individual's name in the branch statistics module, [here](https://github.com/squatteur/webtrees-branch-statistics/blob/e9fb37b3b7c1634a9f67c0bb245289a964eca266/resources/views/chart.phtml#L87).

There is no easy way to detect this from my custom module.

I guess this shows that printing the xref as part of an individual's name is rather hacky - I already regret having added the option in the first place.

Perhaps the other module can add an option to display the xref?

**Comment by hartenthaler** [comment]
... doppeltgemoppelt! 

I can see it now. It is not your problem.
