### ISSUE TITLE
two _FSFTID tags in one record results in error

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_classic_laf#43]
I have accidentally in one record two identical 1 _FSFTID tags. This results in an error, which does not allow editing the raw GEDCOM of this record. Search/Replace allowed me to solve the problem.

`
A DOM node with an ID value "fact-f74bc7cae6931d2fabb8536e10f0e37b" already exists! Pass the HTML5DOMDocument::ALLOW_DUPLICATE_IDS option to disable this check. …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php:197
#0 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(203): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#1 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(203): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#2 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(203): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#3 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(203): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#4 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(203): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#5 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(203): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_extended_relationships#3 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(203): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#7 …/modules_v4/vesta_classic_look_and_feel/IvoPetkov/HTML5DOMDocument.php(207): IvoPetkov\HTML5DOMDocument->IvoPetkov\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#8 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(214): IvoPetkov\HTML5DOMDocument->loadHTML()
vesta-webtrees-2-custom-modules/vesta_personal_facts#9 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(187): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule::strippedLayout()
vesta-webtrees-2-custom-modules/vesta_personal_facts#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process()
vesta-webtrees-2-custom-modules/vesta_personal_facts#11 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
vesta-webtrees-2-custom-modules/vesta_classic_laf#15 …/app/Http/Middleware/AuthEditor.php(57): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthEditor->process()
vesta-webtrees-2-custom-modules/vesta_personal_facts#15 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
vesta-webtrees-2-custom-modules/vesta_personal_facts#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#18 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch()
vesta-webtrees-2-custom-modules/vesta_personal_facts#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
vesta-webtrees-2-custom-modules/vesta_personal_facts#20 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
vesta-webtrees-2-custom-modules/vesta_personal_facts#22 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
vesta-webtrees-2-custom-modules/vesta_personal_facts#24 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#25 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
vesta-webtrees-2-custom-modules/vesta_personal_facts#26 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
vesta-webtrees-2-custom-modules/vesta_personal_facts#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
vesta-webtrees-2-custom-modules/vesta_personal_facts#28 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
`

**Comment by ric2016** [comment]
This seems to be an issue for any duplicated fact or event.
Fix to follow.

**Comment by ric2016** [comment]
Fixed in latest release 2.0.12.0.0.
