### ISSUE TITLE
Space between images

### ISSUE THREAD

**Issue by HRN65** [vesta-webtrees-2-custom-modules/vesta_classic_laf#50]
If a media object contains more than one file, there is no space between the image thumbnails (see attachments)
This is solved by adding these lines to css:

/* Add space between thumbnails */	
	.p-1 .gallery {
	padding-left: 2px;
}

![unmodified](https://user-images.githubusercontent.com/55854079/114612038-e88aa480-9ca1-11eb-8035-e56df1f537c0.png)
![modified](https://user-images.githubusercontent.com/55854079/114612042-e9bbd180-9ca1-11eb-80c7-688a8613bc9e.png)

**Comment by ric2016** [comment]
Good suggestion, I'll add this in the next release.

**Comment by ric2016** [comment]
Implemented in 2.0.15.2.0.
