### ISSUE TITLE
2.0.19.0.0 Census assistant shared notes unformatted

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_classic_laf#60]
When Classic L&F Text formatting Preserve GEDCOM linebreaks ... is ON, then all TEXTs and NOTEs are looking OK, **but census assistant shared notes are not formatted as tables**.

Instead of (as it should look):

![Výběr_240](https://user-images.githubusercontent.com/350656/144757155-e94c48e0-a4e7-41e9-a780-ae71c8f73144.jpg)

the table is not formatted:

![Výběr_241](https://user-images.githubusercontent.com/350656/144757188-7b97e8cb-9c4d-40cc-b949-cd3949cccf7a.jpg)

**Comment by ric2016** [comment]
So much for the suggestion to fix this issue by appending two spaces to each line (that's what Vesta does internally). 

Apparently, '.start_formatted_area.' is a leftover from webtrees 1.x? If I create a shared note with the census assistant now, it seems to be ok. Can you confirm this?

Can you post the GEDCOM snippet of the webtrees 1.x note?

**Comment by jpretired** [comment]
GEDCOM snippet of the above shared note:

`0 @N4@ NOTE 1880 Česko - Přepis sčítacího archu - Matouš Špunda - Lutín č. 9
1 CONT Lutín č. 9
1 CONT
1 CONT .start_formatted_area.
1 CONT .b.Jméno|.b.Pohlaví|.b.Vztah|.b.Narození|.b.Místo|.b.Přísluší|.b.Vyznání|.b.Stav|.b.Jazyk|.b.Povolání|.b.Postavení|.b.|.b.
1 CONT Matouš Špunda|M|hlava domu|30/1 1856|Lutín|Lutín|katolík|ženatý|moravský|rolník|půlláník|
1 CONT Filomena Špundová|Ž|manželka|13/5 1861|Lutín|Lutín|katolička|vdaná|moravský||vede hospodářství|
1 CONT Rudolf Špunda|M|syn|6/12 1880|Lutín|Lutín|katolík|svobodný|moravský|||
1 CONT Matěj Bartoněk|M||1859|Rataje|Rataje|katolík|svobodný|moravský|sloužící|pacholek|
1 CONT Filoména Vybíralová|Ž||24/10 1862|Lutín|Lutín|katolička|svobodná|moravský|služebná|děvečka|
1 CONT .end_formatted_area.
1 CONT
1 CONT Sčítací arch obsahuje také počty hospodářských zvířat.
1 CONT
1 CHAN
2 DATE 28 SEP 2018
3 TIME 21:08:18
2 _WT_USER admin
`

**Comment by jpretired** [comment]
GEDCOM snippet of the above shared note:

0 @N4@ NOTE 1880 Česko - Přepis sčítacího archu - Matouš Špunda - Lutín č. 9
1 CONT Lutín č. 9
1 CONT
1 CONT .start_formatted_area.
1 CONT .b.Jméno|.b.Pohlaví|.b.Vztah|.b.Narození|.b.Místo|.b.Přísluší|.b.Vyznání|.b.Stav|.b.Jazyk|.b.Povolání|.b.Postavení|.b.|.b.
1 CONT Matouš Špunda|M|hlava domu|30/1 1856|Lutín|Lutín|katolík|ženatý|moravský|rolník|půlláník|
1 CONT Filomena Špundová|Ž|manželka|13/5 1861|Lutín|Lutín|katolička|vdaná|moravský||vede hospodářství|
1 CONT Rudolf Špunda|M|syn|6/12 1880|Lutín|Lutín|katolík|svobodný|moravský|||
1 CONT Matěj Bartoněk|M||1859|Rataje|Rataje|katolík|svobodný|moravský|sloužící|pacholek|
1 CONT Filoména Vybíralová|Ž||24/10 1862|Lutín|Lutín|katolička|svobodná|moravský|služebná|děvečka|
1 CONT .end_formatted_area.
1 CONT
1 CONT Sčítací arch obsahuje také počty hospodářských zvířat.
1 CONT
1 CHAN
2 DATE 28 SEP 2018
3 TIME 21:08:18
2 _WT_USER admin

**Comment by ric2016** [comment]
Thank you - I was able to reproduce the issue. Should now be fixed in the latest release 2.0.19.0.1.

**Comment by jpretired** [comment]
Thank you, Richard.
Now it looks OK.
