### ISSUE TITLE
Markdown double line breaks (v2.0.19.0.2)

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_classic_laf#62]
Vielen Dank, aber das war jetzt zu viel. In Notizen wird nun statt eines Zeilenumbruchs noch eine zusätzliche Leerzeile eingefügt.

In v2.0.19.0.1 hatte ich noch keine fehlerhafte bzw. nicht korrigierte Darstellung gefunden.

**Comment by ric2016** [comment]
Kann ich gerade lokal nicht nachvollziehen - Liegt das womöglich an einem zusätzlichen Versuch, das Problem via CSS zu beheben, wie ja auch vorgeschlagen wurde? Oder hat sich die Anzeige tatsächlich mit der neuesten Vesta-Version geändert?

Dann bitte ich um einen Beispiel-GEEDCOM-Schnipsel, um das reproduzieren zu können.
(In 2.0.19.0.1 war der Text von Quellenzitaten noch nicht korrekt.)

**Comment by mpwt** [comment]
Es sind nur die Quellenzitattexte (5 CONT).

<img width="914" alt="Bildschirmfoto 2021-12-06 um 20 19 49" src="https://user-images.githubusercontent.com/16311627/144908737-4b2b207f-afb1-4ab0-a432-df7f0e01f01f.png">

```
1 OCCU Drängen
2 DATE 09 DEC 1867
2 PLAC Ystad, Skåne, Schweden
2 SOUR @S170@
3 PAGE Inflyttnings-Längd 1867, ohne Nr.
3 DATA
4 TEXT [Års-numer.] <leer>
5 CONT [Inskrifningsdag.] [9/12]
5 CONT [Folio uti Förhörsboken.] <leer>
5 CONT [De Utflyttydes namn, stånd, embete, yrke.] [Dr] Ola Månsson
5 CONT [Ort, hvarthän inflyttad, (socken i Län, stad.] Y.S.P. [Ystad St. Petri]
5 CONT [Ställe, hvarifrån inflyttad.] Ångqvarn
5 CONT [Mankön.] 1
5 CONT [Qvinkön.] <leer>
5 CONT
2 ADDR Ångqvarn
```

**Comment by ric2016** [comment]
Ich kann es mit dem JustLight-Theme reproduzieren (in den Standard-Themes sieht es ok aus).
Das Theme habe ich nun aus dem Screenshot geraten - bitte möglichst immer mit angeben, ob andere Cistom modules verwendet werden!

Im JustLight-Theme wird tatsächlich spezielles CSS dafür verwendet (was aber nicht an allen Stellen mit Markdown-Formatierung im GEDCOM greift):

`.markdown p {
    white-space: pre-wrap;
}`

Die Lösung dieses Konflikts zwischen zwei Custom Modules ist mir noch nicht klar.

**Comment by mpwt** [comment]
Vielen Dank für Ihre Mühe. Oft überblickt man als Nutzer gar nicht, welche Informationen zur Klärung notwendig sein könnten.

Es stimmt, dass mit Justlight die Quellenzitattexte (5 CONT) schon korrigiert werden, jedoch nicht auf den anderen Ebenen und ggf. Zuordnungen (NOTE vs. TEXT). Daher funktioniert die Version 2.0.19.0.1 Ihres Addons mit Justlight auch schon super.

Vermutlich ist dies auch der Grund, warum mit der von Greg veröffentlichten CSS-Ergänzung für "almost markdown" die verursachten Darstellungsänderungen nicht in allen Ebenen behoben werden kann.

**Comment by ric2016** [comment]
Ja, die vorgeschlagenen Lösungen sind alle nicht umfassend. Ich fasse das vielleicht im Forum nochmal zusammen.

Ich lasse das Ticket noch offen - Wahrscheinlich baue ich noch eine zusätzliche Option ein, so daß man bei Verwendung von CSS diese 'doppelten' Behandlungen vermeiden kann.

**Comment by mpwt** [comment]
Ich habe mir die CSS-Datei in Theme Justlight angeschaut und einen doppelten Eintrag für .markdown p gefunden. Den einen hatte die Autorin gerade gelöscht, für den anderen habe ich ihr jetzt einen Pull request geschickt. Nach einem lokalen Test wäre der Konflikt mit v2.0.19.0.2 Ihres Moduls dann offensichtlich behoben.

**Comment by ric2016** [comment]
Fixed in 2.0.19.0.3.
