### ISSUE TITLE
Error in in Favourites module when using Classic LAF

### ISSUE THREAD

**Issue by HRN65** [vesta-webtrees-2-custom-modules/vesta_classic_laf#74]
Using Classic LAF in webtrees 2.1.0-beta.2, there seems to be an error in the Favourites module.
The info in the individual boxes is not displayed correctly.

![220535](https://user-images.githubusercontent.com/55854079/162824098-8f796f3e-b09a-42f6-9e5a-545879df2bf2.jpg)
![220717](https://user-images.githubusercontent.com/55854079/162824100-f847e417-1235-474e-8f06-f867a54e079f.jpg)

**Comment by ric2016** [comment]
Should be fixed in latest release.
