### ISSUE TITLE
Side panel distorted

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_classic_laf#78]
webtrees 2.1.2, vesta 2.1.1.0.0, (edit: 2.1.1.0.1 too).
Vesta_laf preferences: Individual page > Use compact layout checked (enabled).
On individual page side panel is distorted:

![Výběr_264](https://user-images.githubusercontent.com/350656/166924883-6826159c-ed57-44dc-ba81-527035319bbf.jpg)

**Comment by ric2016** [comment]
Fixed in latest release 2.1.2.0.0.
