### ISSUE TITLE
Last version of Vesta modules not compatible with webtrees 2.0.23?

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_classic_laf#81]
There is an error after uploading the latest version of Vesta modules to a 2.0.23 installation
`Error: Call to undefined method Fisharebest\Webtrees\Registry::routeFactory() in /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php:190 Stack trace: #0 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/vesta_common/VestaModuleTrait.php(259): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->onBoot() #1 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Services/ModuleService.php(866): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->boot() #2 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/BootModules.php(60): Fisharebest\Webtrees\Services\ModuleService->bootModules() #3 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process() #4`

**Comment by ric2016** [comment]
Fix in latest release 2.1.2.1.2.
