### ISSUE TITLE
v2.0.5.0.0 - vesta_classic_look_and_feel prevents startup webtrees

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#9]
After updating the Vesta modules to v2.0.5.0.0, webtrees will no longer appear.
After removing the **vesta_classic_look_en_feel** module, webtrees reappears.

_Tested configuration_
Device: desktop pc
OS: Windows10 x64 Home v1909
Browsers: Edge v83.0.478.44 and Firefox v77.0.1
webtrees: 2.0.5
PHP: 7.3.17-1

**Comment by ric2016** [comment]
I cannot reproduce this.
Can you check your php error log? There should be something there that indicates the problem. Alternatively, try re-installing this particular module.

**Comment by TheDutchJewel** [comment]
> Can you check your php error log?

Where can I find the php error log? No error in the Control panel > Website logs

> Alternatively, try re-installing this particular module.

Already done, but without success.

The problem is in the file **module.php**: if I only delete that file, webtrees appears.
Maybe it has a problem with the number 2 in the local path (D:\xampp\htdocs\webtrees2\modules_v4\vesta_classic_look_and_feel\module.php).

**Comment by jpretired** [comment]
I have the same issue as TheDutchJewel.

**Comment by ric2016** [comment]
ok, I'll investigate further.

Have you used the 'compact_themes_adjuster' module before? Is that module now disabled, or its folder removed?

Regarding the error log: In general, see here: https://webtrees.net/faq/500/
You may be able to determine the location of the error log file via Control Panel >  Server information, or via your php.ini file (search for 'error_log').

**Comment by jpretired** [comment]
I have used the compact_theme_adjuster before.
I disabled it and deleted its folder before installing vesta_laf.

**Comment by TheDutchJewel** [comment]
>Have you used the 'compact_themes_adjuster' module before?

No.

>Is that module now disabled, or its folder removed?

It's disabled and the folder exists.

**Comment by TheDutchJewel** [comment]
> Control Panel > Server information > 'error_log'

\xampp\php\logs\php_error_log

But that logs folder does not exist, so no error found.

**Comment by ric2016** [comment]
ok, can you check your php.ini (location should be "\xampp\php\php.ini"), you may have to enable error logging:
log_errors=On

**Comment by ric2016** [comment]
@jpretired This isn't quite the same issue, as you don't seem to get a blank page.
Have you tried to re-upload the module folder?
Can you check your php error log?

**Comment by jpretired** [comment]
I do get a blank page. I reinstalled the module twice, no change.
> Can you check your php error log?
I added these to .htaccess:
`php_flag display_errors on
php_flag display_startup_errors on
php_value error_reporting -1`
No errors in my php_errors.log

**Comment by ric2016** [comment]
Hmmm, tricky - which php version do you use?
The blank page is returned via Http Response Code 500? Is there anything else in the response?

**Comment by ric2016** [comment]
@jpretired Just to make sure: You are on webtrees 2.0.5?

**Comment by jpretired** [comment]
yes, webtrees 2.0.5
PHP Version 7.2.24-0ubuntu0.18.04.6

> The blank page is returned via Http Response Code 500?

No, just blank page.

**Comment by ric2016** [comment]
Sorry, but I'm running out out of ideas how to solve this without an error message.
We'll have to wait for others to encounter the same issue, unfortunately - or you'll have to find out how to configure your system to log the respective error message: There has to be one.

In general I think it's easier to handle error logging via php.ini (in particular on local systems, such as xampp), rather than via .htaccess. Make sure you have the correct location of your error log, then create some dummy log entry (just add `error_log("xyz");` somewhere in webtrees, e.g. in index.php), then make sure this entry appears in the error log, as expected.

Once you have established the error logging basically works as expected, re-enable the module and re-check the error log.

**Comment by ric2016** [comment]
The latest Vesta release may fix this issue, can you test this?

**Comment by jpretired** [comment]
Looks like it is WORKING!! - thanks Richard!
Note:
so far I installed vesta_classic_laf and vesta_common modules only. Not the others.

**Comment by TheDutchJewel** [comment]
Same for me: problem fixed with v2.0.5.0.2!
Thank Richard!

**Comment by ric2016** [comment]
Thank you all for testing.
By the way, I have raised the error reporting issue [here](https://github.com/fisharebest/webtrees/issues/3328), that will make it easier in the future.
