### ISSUE TITLE
Option to append XREF to family name does not work - instead it enables option for Individuals

### ISSUE THREAD

**Issue by Neriderc** [vesta-webtrees-2-custom-modules/vesta_classic_laf#90]
With this option to enable displaying the XREF on the family name, if enabled and saved, it enables the option for individuals and for families, but only actually works for individuals. It also says "Individual" in the text under the family option.

![image](https://user-images.githubusercontent.com/89974636/181647200-ab1e9b62-7c6b-4c7f-8f8f-d71bb430b357.png)

The family page does not show the XREF:
![image](https://user-images.githubusercontent.com/89974636/181647325-776f72d0-5d95-4cbc-9f9c-53a3d003523e.png)

It looks like both options submit the same value for the same option:
![image](https://user-images.githubusercontent.com/89974636/181647828-07081d35-9e89-4ae8-95a5-a13d77e5370d.png)

It looks like perhaps an error has been made, accidentally copying the "individual" setting over the setting to add XREF to families?

**Comment by ric2016** [comment]
Yes, it seems so. I'll have to investigate this.

**Comment by ric2016** [comment]
Fixed in latest Vesta release 2.1.7.0.0.
