### ISSUE TITLE
no compatible with webtrees 2.1.7

### ISSUE THREAD

**Issue by HonkXL** [vesta-webtrees-2-custom-modules/vesta_classic_laf#91]
After upgrade to webtrees 2.1.7 all vesta modules have been disabled.

**Comment by ric2016** [comment]
This is by design. They are technically not disabled, by the way, but do not provide any functionality in order to avoid errors due to incompatible code changes in webtrees.

See description in control panel. Solution, as always: Wait for the next Vesta release.
