### ISSUE TITLE
Highlight filled tabs

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_classic_laf#92]
Filled tabs such as Facts and Events, Families, Sources, Notes, etc. should be highlighted in bold if entries are present.

Best regards
Peter

**Comment by ric2016** [comment]
Tabs without content are already handled by webtrees via the class "text-muted". Themes may then present those tabs in special manner. The distinction isn't very visible in the standard theme, but it is visible in others.

I don't think there is anything to do here for Vesta?
