### ISSUE TITLE
Scrolling indi images

### ISSUE THREAD

**Issue by HRN65** [vesta-webtrees-2-custom-modules/vesta_classic_laf#94]
In vesta_classic_look_and_feel/resources/views/individual-page-images.phtml line 51, please change
`<div id="individual-images" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">`
to `<div id="individual-images" class="carousel slide" data-bs-interval="false">`

See https://github.com/fisharebest/webtrees/issues/4516

**Comment by arbor95** [comment]
Merci

**Comment by Mabba64** [comment]
Thanks

**Comment by ric2016** [comment]
THank you for the detailed instructions - Fixed in latest Vesta release 2.1.7.0.1.
