### ISSUE TITLE
Error: Call to undefined method Cissee\...::setAppendXref()

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_classic_laf#97]
vesta modules 2.1.7.0.2, webtrees 2.1.7, PHP 8.1.
Please help!

Error: Call to undefined method Cissee\WebtreesExt\IndividualNameHandler::setAppendXref() in /hosting/www/jprodina.cz/demo/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php:185
Stack trace:
#0 /hosting/www/jprodina.cz/demo/modules_v4/vesta_common/VestaModuleTrait.php(259): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->onBoot()
#1 /hosting/www/jprodina.cz/demo/app/Services/ModuleService.php(910): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->boot()
#2 /hosting/www/jprodina.cz/demo/app/Http/Middleware/BootModules.php(58): Fisharebest\Webtrees\Services\ModuleService->bootModules()
#3 /hosting/www/jprodina.cz/demo/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#4 /hosting/www/jprodina.cz/demo/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#5 /hosting/www/jprodina.cz/demo/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#6 /hosting/www/jprodina.cz/demo/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#7 /hosting/www/jprodina.cz/demo/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process() #8 /hosting/www/jprodina.cz/demo/app/Http/Middleware/CheckForNewVersion.php(65): Middleland\Dispatcher->handle() #9 /hosting/www/jprodina.cz/demo/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process() #10 /hosting/www/jprodina.cz/demo/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle() #11 /hosting/www/jprodina.cz/demo/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #12 /hosting/www/jprodina.cz/demo/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction() #13 /hosting/www/jprodina.cz/demo/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()

**Comment by ric2016** [comment]
I'm afraid I cannot reproduce this. 
I can only suggest to check whether your IndividualNameHandler.php file is sonehow not up-to-date (webtrees\modules_v4\vesta_classic_look_and_feel\patchedWebtrees\IndividualNameHandler.php).

**Comment by ric2016** [comment]
Any update on this?

**Comment by jpretired** [comment]
The error seems to disappear after I followed your advice to replace the file IndividualNameHandler.php.
